### ISSUE TITLE
sqlite cannot open a database file

### ISSUE THREAD

**Issue by yampelo** [JamesHabben/evolve#1]
Hey,

Regardless if what location i run the script from, i always get the same error: 'sqllite3.OperationalError: unable to open database file"

I've tried running from /tmp/ /opt/ /usr/bin/ and against multiple different memory images.

**Comment by JamesHabben** [comment]
Hi Omer,
The sqlite file gets dropped beside the ram image. Is it possible that you are reading from a read only folder or drive?

**Comment by yampelo** [comment]
Nope, i'm the owner of the folder which contains the memorydump and i have read/write/execute on it, tried running it as root aswell. 

Is there anything i need to do volatility on the file to generate a database file or does evolve do that byitself?

**Comment by JamesHabben** [comment]
Evolve has volatility create the db when it runs the modules, if it is needed. I have a thought that I will check out. Will let you know later.

**Comment by ethanf0725** [comment]
Hi James,

I'm having a similar issue.  I'm running the script via Windows 7, which perhaps is part of the issue, but to my knowledge have everything installed correctly.  It fails to create the database file, and I'm receiving the following error:

Traceback (most recent call last):
  File "evolve.py", line 83, in <module>
    BuildPluginList()
  File "evolve.py", line 43, in BuildPluginList
    con = sqlite3.connect(config.OUTPUT_FILE)
sqlite3.OperationalError: unable to open database file

Thanks

**Comment by JamesHabben** [comment]
Omer,
Are you also on Windows?

**Comment by yampelo** [comment]
Nope, ubuntu 12.04 LTS

**Comment by JamesHabben** [comment]
I finally found a Windows VM with no python and found the problem. I committed a change that should fix it for you. Let me know!

Thanks for checking it out!

**Comment by yampelo** [comment]
Cool thanks, i'll check it out sunday morning and tell you if it worked

**Comment by ethanf0725** [comment]
this solved the issues I was having.  thanks, great tool, great work.  excited to see more!

**Comment by JamesHabben** [comment]
Great! I will keep this open until we can confirm with Omer also.

Thanks to both of you for the feedback!

**Comment by yampelo** [comment]
Hey, thanks it fixed it but i have a couple of propsel's im gonna suggest in a new issue
