### ISSUE TITLE
Cannot run and view plugins from Volatility

### ISSUE THREAD

**Issue by rprasko** [JamesHabben/evolve#9]
Hi all,

I just installed Evolve onto my Linux Ubuntu 14.04 machine and have been trying to feed memory dumps such as the stuxnet.vmem file from the Volatility Public Memory Images at (https://code.google.com/p/volatility/wiki/PublicMemoryImages). I am able to start the Web Interface and show all plugins available from Volatility. Anytime that I click run it will run but no results will be produced. Looking at the web interface terminal it gives me the following output:

printkey: 'PrintKey' object has no attribute 'render_sqlite'

I have installed bottle-SQLite. Not really sure where my issue is arising. If anyone could help it would be greatly appeciated.

Thanks

**Comment by JamesHabben** [comment]
Make sure you have the latest version of Volatility. This is the most common problem I have seen with the 'render_sqlite' errors. Vol version numbers don't account for patches and updates, so 2.4 stays constant even though code has been updated.

**Comment by rprasko** [comment]
That fixed that issue, now it is not giving me attribute errors but no it states the following:

pslist: No suitable address space mapping found

**Comment by JamesHabben** [comment]
Just to baseline the obvious, you are providing a profile name?

**Comment by rprasko** [comment]
Yes, I'm using --profile WinXPSP2x86

**Comment by JamesHabben** [comment]
Try it with -p instead of --profile. Just curious if I am causing the problem in the way I handle the parameter name.

**Comment by rprasko** [comment]
It appears that the -p parameter works, I'm able to use the Volatility plugins and create the report. Greatly appreciated, thank you!

**Comment by JamesHabben** [comment]
Thanks for posting this to let me know. I will update the docs until I can fix the code.

**Comment by copeland3300** [comment]
Hey, I'm also having this issue on Kali 2. I've removed the volatility that it ships with, and installed the latest from the Volatility Foundation's website, but I'm still getting the no attribute error.
